# fly.toml app configuration file generated for vlaskz-maybepad on 2023-07-28T23:31:44-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vlaskz-maybepad"
primary_region = "gru"

[build]
  image = "vlaskz/maybepad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
